### PR TITLE
refactor: fixed readme

### PR DESCRIPTION
**Pull request by j4ckson4800**
Fixed readme

### CODE REVIEW

**Review by es3n1n — APPROVED** [review]

**Comment by j4ckson4800** [comment]
@0xfedcafe lgtm

**Comment by sadsadsalt** [comment]
looks good to this dude
image

**Comment by j4ckson4800** [comment]
Almost good except "Pizdabol". Remove this insult.

_Originally posted by @0xfedcafe in https://github.com/0xfedcafe/0xfedcafe/issues/2#issuecomment-1890444770_

**Comment by j4ckson4800** [comment]
@0xfedcafe

**Comment by sadsadsalt** [comment]
image

**Comment by sadsadsalt** [comment]
image

**Comment by sadsadsalt** [comment]
image

**Pull request closed without merging**
