### PR TITLE
refactor: fixed readme

### PR DESCRIPTION
**Pull request by j4ckson4800**
Fixed readme

### CODE REVIEW

**Review by es3n1n — APPROVED** [review]

**Comment by sadsadsalt** [comment]
cocaine hokers hitler right dead nigger monkey fucky wacky red pilled monkey nazi ukraine biden trump iq maxxed
image

**Comment by 0xfedcafe** [comment]
Almost good except "Pizdabol". Remove this insult.

**Comment by sadsadsalt** [comment]
image
image
image
image
image
image

**Comment by sadsadsalt** [comment]
image
image
image
image
image
image
imageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimage

**Comment by sadsadsalt** [comment]
imageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimageimage

**Pull request closed without merging**
